name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
      - run: |
          yarn install
          yarn build
          yarn test
