name: Build, Test, Deploy

on: [push, pull_request]

jobs:
  build-and-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn e2e:headless
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: "next-build"
          path: |
            build.zip 
            .next 
            package.json 
            yarn.lock 
            .env** 
            next.config.js

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn test
  
  deploy:
    runs-on: ubuntu-latest
    needs: [unit-test, build-and-e2e-test]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: "next-build"
          path: "next-build"
      - run: ls -al next-build
      - uses: appleboy/scp-action@master
        with:
          host: ${{secrets.STORYBOOK_HOST}}
          username: ${{secrets.STORYBOOK_USER}}
          key: ${{ secrets.STORYBOOK_KEY }}
          source: next-build
          target: "~/"
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STORYBOOK_HOST }}
          username: ${{ secrets.STORYBOOK_USER }}
          key: ${{ secrets.STORYBOOK_KEY }}
          script: |
            unzip -o ~/next-build.zip -d ~/next-build