name: Build, Test, Deploy

on: [push, pull_request]

jobs:
  build-and-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn e2e:headless

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn test
  
  deploy:
    runs-on: ubuntu-latest
    needs: [unit-test, build-and-e2e-test]
    steps:
      - uses: actions/checkout@v2
      - uses: appleboy/scp-action@master
        with:
          host: ${{secrets.STORYBOOK_HOST}}
          username: ${{secrets.STORYBOOK_USER}}
          key: ${{ secrets.STORYBOOK_KEY }}
          source: ./
          target: "~/storefront"
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STORYBOOK_HOST }}
          username: ${{ secrets.STORYBOOK_USER }}
          key: ${{ secrets.STORYBOOK_KEY }}
          script: |
            cd ~/storefront
            docker-compose down
            docker-compose up --build -d