name: Build and deploy Storybook

on:
  push:
    branches:
      - main
      - dev
    paths: ["src/**"]

jobs:
  buid-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
      - run: yarn install
      - run: yarn build-storybook
      - run: apt-get update -y
      - run: apt-get install zip -y
      - run: zip -r storybook_build.zip ./storybook-static
      - uses: appleboy/scp-action@master
        with: 
          host: ${{secrets.STORYBOOK_HOST}}
          username: ${{secrets.STORYBOOK_USER}}
          key: ${{ secrets.STORYBOOK_KEY }}
          source: "storybook_build.zip,docker-compose-storybook.yml"
          target: "~/storybook/"
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STORYBOOK_HOST }}
          username: ${{ secrets.STORYBOOK_USER }}
          key: ${{ secrets.STORYBOOK_KEY }}
          script: |
            apt-get update -y
            apt-get install unzip -y
            cd ~/storybook
            unzip storybook_build.zip
            docker-compose -f docker-compose-storybook.yml up -d
      

