name: Build and deploy Storybook

on:
  push:
    branches:
      - main
      - dev
    paths:
      [
        "src/**",
        ".storybook/**",
        "i18n/**",
        "public/**",
        ".github/workflows/deploy-storybook.yml",
        "config/**",
        "testUtils/**",
        package.json,
      ]

jobs:
  buid-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
      - run: yarn install
      - run: rm -rf storybook-static
      - run: rm -rf storybook_build.zip
      - run: yarn build-storybook
      - run: zip -r storybook_build.zip ./storybook-static
      - uses: appleboy/scp-action@master
        with:
          host: ${{secrets.STORYBOOK_HOST}}
          username: ${{secrets.STORYBOOK_USER}}
          key: ${{ secrets.STORYBOOK_KEY }}
          source: "storybook_build.zip,docker-compose-storybook.yml"
          target: "~/storybook/"
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STORYBOOK_HOST }}
          username: ${{ secrets.STORYBOOK_USER }}
          key: ${{ secrets.STORYBOOK_KEY }}
          script: |
            rm -rf ~/mysites/www/sb-beauty-store/*
            unzip -o ~/storybook/storybook_build.zip -d ~/mysites/www/sb-beauty-store
            cd ~/mysites/www/sb-beauty-store
            mv storybook-static/* .
            rm -rf storybook-static
